language: node_js
node_js: node
script:
- npm run lint
deploy:
  on:
    tags: true
  provider: npm
  email: layerssss@gmail.com
  api_key:
    secure: dcY7V13r9oBx4MD+tAerBRHlgDHDV9sLNyauC86oTJTC/f5J9V/JXR1hg5zBI+dLzAeRVjsZhGVVMPFKdhHzZvpy4iW1+q/BCF6q28n9wa5CH4WlRbTR5AX2V/1bqby2lQp+Of1BgCyGihJXMNpwYqWNNB3e7TVQM9lMOk7ZpNpIXbf+mTM6W+l0dPxsDlkPytwH3YVWAxV6kgeiAhY8ULnwcjQSOc7AGcFIalHN3V/xgWBEpKyITmauVZG/hb47oiwBJAvc+FwUH0r8YceWvqWFWM6uqxvRFE41EpRfQXlOYgxTzy6XuGPsuuUzTzB2ZmRsunCJ2s0zxGfqPerRotpebt4/76gZToEnkX5qsG1s64BLBPyaI3P1Bif6ywMXoQ/oiIZP4vINKbf4IYl9+lFWonADtlZjpSA8VppdxaMyAMCN2oOesqsYa3PLI24sHBG1xJ3Ub5bjqx5dSNTz5na2gtouD8T2o3chYBvCHq4R48qTrhl8rYtmHTRnEb0XJ73s6tncCh9Jy1CV6TuR5PoA0YwIFXnzbAgyoGP5g3DGwiVPMyfrbQcu/fZIn5UruSHgx8zHw9M2K/Nb6N+3E/bpfOm9v4uvABQN0MBF1Amqx/WaB1ze4K/s6Al+xibghPxdST7d7yvjSSzIRjsYSiefBdoWO7eGofwVKrnuLXI=
